greeting:
        name: CSI Config Service From GIT
        id: csi-config-service-git
        description: CSI Configurations Management Service maintain by GITHUB
        message: Hello There...!!! This is the Configurational Server Message From GITHUB

datasource:
        url: "jdbc:mysql://localhost:3306/configurator-GITHUB"
        username: root-fromGITHUB
        password: root@12345-GITHUB


