greeting:
        name: CSI Config Service From Config Service
        id: csi-config-service
        description: CSI Configurations Management Service maintain by Config Service
        message: Hello There...!!! This is the Configurational Server Message From Config Service

datasource:
        url: "jdbc:mysql://localhost:3306/configurator-fromconfig"
        username: root-fromconfig
        password: root@12345-fromconfig

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CSI_DB_USER
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
