greeting:
        name: CSI Config Service From Config Service
        id: csi-config-service
        description: CSI Configurations Management Service maintain by Config Service
        message: Hello There...!!! This is the Configurational Server Message From Config Service

datasource:
        url: "jdbc:mysql://localhost:3306/configurator-fromconfig"
        username: root-fromconfig
        password: root@12345-fromconfig

spring:
    cloud:
        gateway:
            routes:
            -   id: CSI-MOVIE-CATALOG
                predicates:
                - Path=/api/v1/**
                uri: lb://CSI-MOVIE-CATALOG
            -   id: CSI-MOVIE-INFO
                predicates:
                - Path=/api/v1/**
                uri: lb://CSI-MOVIE-INFO
            -   id: CSI-MOVIE-RATING
                predicates:
                - Path=/api/v1/**
                uri: lb://CSI-MOVIE-RATING
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
