greeting:
  name: CSI Config Service From Config Service
  id: csi-config-service
  description: CSI Configurations Management Service maintain by Config Service
  message: >-
    Hello There...!!! This is the Configurational Server Message From Config
    Service
datasource:
  url: 'jdbc:mysql://localhost:3306/configurator-fromconfig'
  username: root-fromconfig
  password: root@12345-fromconfig

  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://dev-77584981.okta.com/oauth2/default'
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa7w65a24Px9Oyms5d7
            client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU
        provider:
          okta:
            issuer-uri: 'https://dev-77584981.okta.com/oauth2/default'
  datasource:
    url: 'jdbc:mysql://localhost:3306/CSI_DB_USER'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
okta:
  oauth2:
    issuer: 'https://dev-77584981.okta.com/oauth2/default'
    audience: 'api://default'
